[wip] Parser
jwang61/hippogriff pull request #5
Opened 2019-07-09 05:10 UTC by s4ayub

2019-07-18 04:11 UTC, jwang61 commented
This closes #4

2019-07-18 04:13 UTC, jwang61 requested changes
![image](https://user-images.githubusercontent.com/17051406/61428601-bb943c80-a8d7-11e9-801f-84b0f1a92971.png)

Please see requested changes.

2019-07-18 04:13 UTC, jwang61 commented on src/Parse.hs
> +import qualified AST as AST
Don't need `as AST`

2019-07-18 04:13 UTC, jwang61 commented on src/Lex.hs
>  import qualified Data.Char as Char
Don't need `as Char`

2019-07-18 04:14 UTC, jwang61 commented on src/Lex.hs
>  import qualified Data.Char as Char
Take that back, you do.

2019-07-18 04:26 UTC, s4ayub commented on src/Lex.hs
>  import qualified Data.Char as Char
you're crazy

2019-07-23 01:32 UTC, jwang61 approved these changes

2019-07-23 01:33 UTC, merged